Repository easyscience/EasyReflectometryLib, pull requests merged in 2025-03, with the labels that each got.

#210 Tutorial- og Layout update
  docs/src/calculators.rst
  docs/src/dictionay.rst
  docs/src/index.rst
  docs/src/tutorials/advancedfitting/multi_contrast.ipynb
  docs/src/tutorials/advancedfitting/multiple.ort
  docs/src/tutorials/basic/assemblies_library.rst
  docs/src/tutorials/basic/layer_library.rst
  docs/src/tutorials/basic/material_library.rst
  docs/src/tutorials/basic/model.rst
  docs/src/tutorials/basic/sample.rst
  docs/src/tutorials/fitting/dspc.png
  docs/src/tutorials/fitting/material_solvated.ipynb
  docs/src/tutorials/fitting/mod_pointwise_two_layer_sample_dq-0.0.ort
  docs/src/tutorials/fitting/mod_pointwise_two_layer_sample_dq-1.0.ort
  docs/src/tutorials/fitting/mod_pointwise_two_layer_sample_dq-10.0.ort
  docs/src/tutorials/fitting/monolayer.ipynb
  docs/src/tutorials/fitting/monolayer.png
  docs/src/tutorials/fitting/monolayer.svg
  docs/src/tutorials/fitting/repeating.ipynb
  docs/src/tutorials/fitting/simple_fitting.ipynb
  docs/src/tutorials/project.ipynb
  docs/src/tutorials/sample/d70d2o.ort
  docs/src/tutorials/sample/multi_contrast.ipynb
  docs/src/tutorials/simulation/magnetism.ipynb
  docs/src/tutorials/simulation/resolution_functions copy.ipynb
  docs/src/tutorials/simulation/resolution_functions.ipynb
  docs/src/tutorials/simulation/two_layers.png
  docs/src/tutorials/simulation/two_layers.svg
  docs/src/tutorials/tutorials.rst
  docs/src/usage.rst
Labels: documentation

#209 New parameter and numpy2
  .github/workflows/documentation-build.yml
  .github/workflows/python-ci.yml
  .github/workflows/python-package.yml
  .github/workflows/python-publish.yml
  CONTRIBUTING.rst
  pyproject.toml
  src/easyreflectometry/calculators/refl1d/wrapper.py
  src/easyreflectometry/model/model.py
  src/easyreflectometry/project.py
  src/easyreflectometry/sample/assemblies/repeating_multilayer.py
  src/easyreflectometry/sample/assemblies/surfactant_layer.py
  src/easyreflectometry/sample/elements/layers/layer.py
  src/easyreflectometry/sample/elements/layers/layer_area_per_molecule.py
  src/easyreflectometry/sample/elements/materials/material.py
  src/easyreflectometry/sample/elements/materials/material_density.py
  src/easyreflectometry/sample/elements/materials/material_mixture.py
  src/easyreflectometry/sample/elements/materials/material_solvated.py
  src/easyreflectometry/utils.py
  tests/calculators/refl1d/test_refl1d_wrapper.py
  tests/model/test_model.py
  tests/sample/elements/layers/test_layer.py
  tests/sample/elements/materials/test_material.py
  tests/sample/elements/materials/test_material_density.py
  tests/sample/elements/materials/test_material_solvated.py
  tests/test_parameter_utils.py
  tests/test_project.py
Labels: chore

#211 Merge develop into master
  .github/workflows/documentation-build.yml
  .github/workflows/python-ci.yml
  .github/workflows/python-package.yml
  .github/workflows/python-publish.yml
  CONTRIBUTING.rst
  docs/src/calculators.rst
  docs/src/dictionay.rst
  docs/src/index.rst
  docs/src/tutorials/advancedfitting/multi_contrast.ipynb
  docs/src/tutorials/advancedfitting/multiple.ort
  docs/src/tutorials/basic/assemblies_library.rst
  docs/src/tutorials/basic/layer_library.rst
  docs/src/tutorials/basic/material_library.rst
  docs/src/tutorials/basic/model.rst
  docs/src/tutorials/basic/sample.rst
  docs/src/tutorials/fitting/dspc.png
  docs/src/tutorials/fitting/material_solvated.ipynb
  docs/src/tutorials/fitting/mod_pointwise_two_layer_sample_dq-0.0.ort
  docs/src/tutorials/fitting/mod_pointwise_two_layer_sample_dq-1.0.ort
  docs/src/tutorials/fitting/mod_pointwise_two_layer_sample_dq-10.0.ort
  docs/src/tutorials/fitting/monolayer.ipynb
  docs/src/tutorials/fitting/monolayer.png
  docs/src/tutorials/fitting/monolayer.svg
  docs/src/tutorials/fitting/repeating.ipynb
  docs/src/tutorials/fitting/simple_fitting.ipynb
  docs/src/tutorials/project.ipynb
  docs/src/tutorials/sample/d70d2o.ort
  docs/src/tutorials/sample/multi_contrast.ipynb
  docs/src/tutorials/simulation/magnetism.ipynb
  docs/src/tutorials/simulation/resolution_functions copy.ipynb
  docs/src/tutorials/simulation/resolution_functions.ipynb
  docs/src/tutorials/simulation/two_layers.png
  docs/src/tutorials/simulation/two_layers.svg
  docs/src/tutorials/tutorials.rst
  docs/src/usage.rst
  pyproject.toml
  src/easyreflectometry/calculators/refl1d/wrapper.py
  src/easyreflectometry/model/model.py
  src/easyreflectometry/project.py
  src/easyreflectometry/sample/assemblies/repeating_multilayer.py
  src/easyreflectometry/sample/assemblies/surfactant_layer.py
  src/easyreflectometry/sample/elements/layers/layer.py
  src/easyreflectometry/sample/elements/layers/layer_area_per_molecule.py
  src/easyreflectometry/sample/elements/materials/material.py
  src/easyreflectometry/sample/elements/materials/material_density.py
  src/easyreflectometry/sample/elements/materials/material_mixture.py
  src/easyreflectometry/sample/elements/materials/material_solvated.py
  src/easyreflectometry/utils.py
  tests/calculators/refl1d/test_refl1d_wrapper.py
  tests/model/test_model.py
  tests/sample/assemblies/test_surfactant_layer.py
  tests/sample/elements/layers/test_layer.py
  tests/sample/elements/layers/test_layer_area_per_molecule.py
  tests/sample/elements/materials/test_material.py
  tests/sample/elements/materials/test_material_density.py
  tests/sample/elements/materials/test_material_solvated.py
  tests/special/test_calculations.py
  tests/test_parameter_utils.py
  tests/test_project.py
Labels: feature
