Repository easyscience/EasyReflectometryLib, pull requests merged in 2025-04, with the labels that each got.

#212 Update __version__.py
  .github/workflows/python-publish.yml
  docs/src/api/model.rst
  docs/src/api/sample.rst
  docs/src/conf.py
  pyproject.toml
  src/easyreflectometry/__version__.py
  src/easyreflectometry/data/__init__.py
  src/easyreflectometry/model/__init__.py
  src/easyreflectometry/sample/__init__.py
Labels: dependencies, [scope] maintenance

#215 Trusted publishing for PyPi and dependencies
  .github/workflows/python-publish.yml
  docs/src/api/model.rst
  docs/src/api/sample.rst
  docs/src/conf.py
  pyproject.toml
  src/easyreflectometry/__version__.py
  src/easyreflectometry/data/__init__.py
  src/easyreflectometry/model/__init__.py
  src/easyreflectometry/sample/__init__.py
Labels: dependencies, [scope] maintenance

#216 Docs-fix-w-dev-changes
  .github/workflows/documentation-build.yml
  docs/src/api/data.rst
  docs/src/api/model.rst
  docs/src/api/sample.rst
  docs/src/conf.py
  docs/src/index.rst
  docs/src/tutorials/advancedfitting/advancedfitting.rst
  docs/src/tutorials/advancedfitting/multi_contrast.ipynb
  docs/src/tutorials/basic/assemblies_library.rst
  docs/src/tutorials/basic/basic.rst
  docs/src/tutorials/basic/layer_library.rst
  docs/src/tutorials/basic/material_library.rst
  docs/src/tutorials/basic/model.rst
  docs/src/tutorials/extra/extra.rst
  docs/src/tutorials/fitting/d70d2o.ort
  docs/src/tutorials/fitting/eq_monolayer.svg
  docs/src/tutorials/fitting/eq_solvated.svg
  docs/src/tutorials/fitting/fitting.rst
  docs/src/tutorials/fitting/material_solvated.ipynb
  docs/src/tutorials/fitting/monolayer.ipynb
  docs/src/tutorials/fitting/repeating.ipynb
  docs/src/tutorials/fitting/simple_fitting.ipynb
  docs/src/tutorials/project.ipynb
  docs/src/tutorials/simulation/magnetism.ipynb
  docs/src/tutorials/simulation/mod_pointwise_two_layer_sample_dq-0.0.ort
  docs/src/tutorials/simulation/mod_pointwise_two_layer_sample_dq-1.0.ort
  docs/src/tutorials/simulation/mod_pointwise_two_layer_sample_dq-10.0.ort
  docs/src/tutorials/simulation/resolution_functions copy.ipynb
  docs/src/tutorials/simulation/resolution_functions.ipynb
  docs/src/tutorials/simulation/simulation.rst
  docs/src/tutorials/tutorials.rst
  docs/src/usage.rst
  pyproject.toml
  src/easyreflectometry/data/measurement.py
  src/easyreflectometry/sample/collections/sample.py
Labels: [scope] documentation, dependencies

#217 Hotfix release for new documentation
  .github/workflows/documentation-build.yml
  docs/src/api/data.rst
  docs/src/api/model.rst
  docs/src/api/sample.rst
  docs/src/conf.py
  docs/src/index.rst
  docs/src/tutorials/advancedfitting/advancedfitting.rst
  docs/src/tutorials/advancedfitting/multi_contrast.ipynb
  docs/src/tutorials/basic/assemblies_library.rst
  docs/src/tutorials/basic/basic.rst
  docs/src/tutorials/basic/layer_library.rst
  docs/src/tutorials/basic/material_library.rst
  docs/src/tutorials/basic/model.rst
  docs/src/tutorials/extra/extra.rst
  docs/src/tutorials/fitting/d70d2o.ort
  docs/src/tutorials/fitting/eq_monolayer.svg
  docs/src/tutorials/fitting/eq_solvated.svg
  docs/src/tutorials/fitting/fitting.rst
  docs/src/tutorials/fitting/material_solvated.ipynb
  docs/src/tutorials/fitting/monolayer.ipynb
  docs/src/tutorials/fitting/repeating.ipynb
  docs/src/tutorials/fitting/simple_fitting.ipynb
  docs/src/tutorials/project.ipynb
  docs/src/tutorials/simulation/magnetism.ipynb
  docs/src/tutorials/simulation/mod_pointwise_two_layer_sample_dq-0.0.ort
  docs/src/tutorials/simulation/mod_pointwise_two_layer_sample_dq-1.0.ort
  docs/src/tutorials/simulation/mod_pointwise_two_layer_sample_dq-10.0.ort
  docs/src/tutorials/simulation/resolution_functions copy.ipynb
  docs/src/tutorials/simulation/resolution_functions.ipynb
  docs/src/tutorials/simulation/simulation.rst
  docs/src/tutorials/tutorials.rst
  docs/src/usage.rst
  pyproject.toml
  src/easyreflectometry/data/measurement.py
  src/easyreflectometry/sample/collections/sample.py
Labels: [scope] documentation, dependencies

#219 update __version__.py
  src/easyreflectometry/__version__.py
Labels: dependencies
